# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build the README.md file from single .md files nested under /assests/md_files/

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5
      - name: Echo current directory
        run: pwd
      - name: List files and sundirectories 
        run: ls -R
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: NOW combining Markdown files into one single README.md file
        run: |
          python src/combine_markdown_files.py   
