name: Build README.md from Markdown Files

on:
  push:
    paths:
      - "assets/md_files/**"
      - "src/**"

jobs:
  build-readme:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Enable .sh file 
        run: chmod +x src/combine_markdown_files.sh
        
      - name: Combine Markdown files into README.md
        run: ./src/combine_markdown_files.sh

      - name: Show generated README.md
        run: cat README.md
