name: Build README.md from Markdown Files

on:
  push:
    paths:
      - "assets/md_files/**"
      - "src/combine_markdown_files.py"

jobs:
  build-readme:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Combine Markdown files into README.md
        run: python src/combine_markdown_files.py

      - name: Show generated README.md
        run: cat README.md
