name: Update README

on:
  push:
    branches:
      - main
 #   paths:
 #     - '.assets/**'  
  #schedule:
   # - cron: "0 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true # ensures GITHUB_TOKEN is used

      - name: Make README executable  
        run: chmod +x src/combine_markdown_files.sh
      
      - name: Run README updater 
        run: bash src/combine_markdown_files.sh

      - name: Install Pandoc and XeLaTeX
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert README.md to PDF - gfm interprets Markdown like GitHub does 
        run: |
          pandoc README.md -o README.pdf \
            --from=gfm \
            --standalone \
            --pdf-engine=xelatex \
            -V papersize:a4 \ 
            -V geometry:"margin=0.5in"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git add README.pdf
          git diff --cached --quiet || git commit -m "Automated README update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# EoF 
