name: Update README

on:
  push:
    branches:
      - main
 #   paths:
 #     - '.assets/**'  
  #schedule:
   # - cron: "0 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true # ensures GITHUB_TOKEN is used

      #- name: Make README executable  
      #  run: chmod +x src/combine_markdown_files.sh
      
      - name: Build README from markdown files
        run: |
          input_dir="assets/md_files/"
          output_file="README.md"
          
          # Array of markdown files to concatenate
          files=(
            "introduction.md"
            "education.md"
            "exprience.md"
          )
          
          # Clear or create output file
          > "${output_file}"
          
          # Loop through files and concatenate
          for file in "${files[@]}"; do
            if [ -f "${input_dir}${file}" ]; then
              cat "${input_dir}${file}" >> "${output_file}"
              echo -e "\n\n" >> "${output_file}"
            else
              echo "Warning: ${input_dir}${file} not found, skipping..."
            fi
          done

      #- name: Run README updater 
      #  run: bash src/combine_markdown_files.sh
          
      #- name: Install Pandoc and XeLaTeX
      #  run: |
      #    sudo apt-get update -qq
      #    sudo apt-get install -y pandoc texlive-xetex
      #
      #- name: Convert README.md to PDF - gfm interprets Markdown like GitHub does 
      #  run: |
      #    pandoc README.md -o README.pdf \
      #      --from=gfm \
      #      --standalone \
      #      --pdf-engine=xelatex

      #- name: Create temporary copy for PDF generation
      #  run: cp README.md README_dummy.md

      #- name: Convert HTML images to Markdown for PDF
      #  run: |
      #    sed -i -E 's|<img src="([^"]*)" width="([^"]*)">|![](\1){ width=\2px }|g' README_dummy.md
            
      - name: Create LaTeX header file      
        run: |
          cat > header.tex << 'EOF'
          \usepackage{xcolor}
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhead[L]{\large\textbf{Milad Asgarpour Khansary}}       
          \fancyhead[C]{} 
          \fancyhead[R]{\small\textcolor{red}{Generated on \today\ via GitHub Actions}}   
          \fancyfoot[L]{}
          \fancyfoot[C]{\thepage}
          \fancyfoot[R]{}
          \renewcommand{\headrulewidth}{0.4pt}
          \renewcommand{\footrulewidth}{0.4pt}
          EOF
      
      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:latest
        with:
          args: >-
            --from=gfm
            --output=README.pdf
            --pdf-engine=xelatex
            --include-in-header=header.tex
            --variable=geometry:a4paper
            --variable=geometry:margin=2cm
            --variable=graphics=true
            --variable=linkcolor=blue
            --variable=urlcolor=blue
            --variable=toccolor=blue 
            --syntax-highlighting=tango
            --standalone
            README.md
            
      - name: Clean up temporary files
        run: |
          rm -f header.tex      
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git add README.pdf
          git diff --cached --quiet || git commit -m "Automated README update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# EoF 
