name: Update README PDF

on:
  push:
    branches:
      - main
    paths:
      - README.md  # Only run when README.md changes
  # schedule:
  #   - cron: "0 * * * *"  # (optional) run hourly if you ever enable this

jobs:
  update-readme-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensures GITHUB_TOKEN is used

      - name: Install Pandoc and XeLaTeX
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert README.md to PDF
        run: |
          pandoc README.md -o README.pdf --standalone --pdf-engine=xelatex

      - name: Commit and push README.pdf
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.pdf
          git diff --cached --quiet || git commit -m "Automated README.pdf update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# EoF
